### ISSUE TITLE
Tur sayılarıyla ilgili.

### ISSUE THREAD

**Issue by ShiningTodoroki** [thenorthstar/HaxBall-Simple-F1-Racing-Bot#1]
Tur sayısını arttırmaya kalktığımızda NaN olarak süreyi gösteriyor. Diyelim ki 15 - 20 turluk bir düzenleme yapacağız, bunu nasıl düzeltebiliriz?

**Comment by thenorthstar** [comment]
> Tur sayısını arttırmaya kalktığımızda NaN olarak süreyi gösteriyor. Diyelim ki 15 - 20 turluk bir düzenleme yapacağız, bunu nasıl düzeltebiliriz?

@ShiningTodoroki Botu yaparken 3 turluk bir yarışa göre ayarlamıştım ve o yapıyı dinamik yapmamıştım. Şu anda sadece **limit** değerini değiştirmen yeterli olacak. Botun güncel hâlinde o yapı da şimdi dinamik bir şekilde çalışıyor. Bu arada başka bir sorun olursa yine buradan yazabilirsin.
