### ISSUE TITLE
Ham koddaki haritalarda ve kendi eklediğimiz haritalarda oluşan problem

### ISSUE THREAD

**Issue by ShiningTodoroki** [thenorthstar/HaxBall-Simple-F1-Racing-Bot#2]
Kodun ham halindeki sizin eklediğiniz 2 haritada bir problemimiz var. Birkaç kişiyi sanki fazladan tur atıyormuş gibi, ex: bir tur atıldıktan hemen sonra 0.067 saniyelik bir tur daha atmış gibi gösteriyor ve tur sayısını diğer kişilere göre 1 tur daha fazla gösteriyor. Bazen bu 2 tur da olabiliyor. 
Kendi haritalarımızdan 2 tanesinde daha denedik. İlki Le Mans Bugatti GP'si, ikincisi ise Baku GP'siydi. 
Le Mans'ın problemi: pit yolunu geçtikten sonra oda çöküyor. 
Baku GP'de startı alır almaz oda çöküyor. 
Eğer kayıtlarını isterseniz 3 farklı haritada kaydımız var. Discord'dan skbn#8120 adresinden bana dm atarsanız size ulaştırabilirim.

**Comment by thenorthstar** [comment]
> Kodun ham halindeki sizin eklediğiniz 2 haritada bir problemimiz var. Birkaç kişiyi sanki fazladan tur atıyormuş gibi, ex: bir tur atıldıktan hemen sonra 0.067 saniyelik bir tur daha atmış gibi gösteriyor ve tur sayısını diğer kişilere göre 1 tur daha fazla gösteriyor. Bazen bu 2 tur da olabiliyor. Kendi haritalarımızdan 2 tanesinde daha denedik. İlki Le Mans Bugatti GP'si, ikincisi ise Baku GP'siydi. Le Mans'ın problemi: pit yolunu geçtikten sonra oda çöküyor. Baku GP'de startı alır almaz oda çöküyor. Eğer kayıtlarını isterseniz 3 farklı haritada kaydımız var. Discord'dan skbn#8120 adresinden bana dm atarsanız size ulaştırabilirim.

@ShiningTodoroki 0.067 saniye olayının benzeri benim başıma da 0.05 saniye olarak geldi Vilnius haritasında. Ona bakacağım.

Öbür problem özelinde şunu söyleyebilirim. Harita içeriğindeki değerler (MinX, MaxX vs.) haritadan haritaya değişiyor. Benim bota eklediğim 2 haritada tesadüfen aynı değerler gelmiş olabilir. Yani o değerleri aynı yaptıysanız harita verilerine göre değiştirmeyi deneyin, yine olmuyorsa bir çözüm düşünürüz.

Pit konusu için de şöyle söyleyebilirim, botu pit olayını hesaba katmadan yaptım; zaten ismini **simple** koymamdaki neden buydu. Onun geliştirmesini projeyi **fork**layarak kendiniz de yapabilirsiniz.

Bu arada kayıtları DC'den atabilirsin, ekran görüntüsüyle de destekleyebilirsen daha kolay fikir ve çözüm üretme aşamasına geçebiliriz diye düşünüyorum.

**Comment by thenorthstar** [comment]
> Kodun ham halindeki sizin eklediğiniz 2 haritada bir problemimiz var. Birkaç kişiyi sanki fazladan tur atıyormuş gibi, ex: bir tur atıldıktan hemen sonra 0.067 saniyelik bir tur daha atmış gibi gösteriyor ve tur sayısını diğer kişilere göre 1 tur daha fazla gösteriyor. Bazen bu 2 tur da olabiliyor. Kendi haritalarımızdan 2 tanesinde daha denedik. İlki Le Mans Bugatti GP'si, ikincisi ise Baku GP'siydi. Le Mans'ın problemi: pit yolunu geçtikten sonra oda çöküyor. Baku GP'de startı alır almaz oda çöküyor. Eğer kayıtlarını isterseniz 3 farklı haritada kaydımız var. Discord'dan skbn#8120 adresinden bana dm atarsanız size ulaştırabilirim.

**Troll detection bug**: Fixed at **47:21**
**Lap increment bug**: Fixed at **76:3**
