### ISSUE TITLE
Pit stop problemiyle alakalı.

### ISSUE THREAD

**Issue by ShiningTodoroki** [thenorthstar/HaxBall-Simple-F1-Racing-Bot#3]
Merhaba. Öncelikle bizim için Le Mans pistini entegre ettiğin için teşekkür ederiz. Fakat yine bir sorun oldu, pit yolundan geçerken bu sefer trollingden atılıyorum. Trolling kodunu kaldırdığımızda ise bu sefer bir tur fazladan attık gözüküyor. 
Örneğin: Orada normal yolu 22.1 saniyede dönüyorsak pit çıkışında 1.735 saniye ile 4. turu tamamlayıp 5. tura geçtiğimizi zannediyor. Bunu nasıl önleyebiliriz?

Ayrıca Vilnius, Sucre ve kendi pistlerimiz olan pit stopsuz Hungaroring ve Bahrain'de de kodunuzun güncellenmiş halini test ettik, onlarda hiçbir problem çekmedik. Vilnius ve Sucre'de ikişer defa denememize rağmen yine bir problemle karşılaşmadık. Bilmek istersiniz diye söylemek istedim.

**Comment by thenorthstar** [comment]
> Merhaba. Öncelikle bizim için Le Mans pistini entegre ettiğin için teşekkür ederiz. Fakat yine bir sorun oldu, pit yolundan geçerken bu sefer trollingden atılıyorum. Trolling kodunu kaldırdığımızda ise bu sefer bir tur fazladan attık gözüküyor. Örneğin: Orada normal yolu 22.1 saniyede dönüyorsak pit çıkışında 1.735 saniye ile 4. turu tamamlayıp 5. tura geçtiğimizi zannediyor. Bunu nasıl önleyebiliriz?
> 
> Ayrıca Vilnius, Sucre ve kendi pistlerimiz olan pit stopsuz Hungaroring ve Bahrain'de de kodunuzun güncellenmiş halini test ettik, onlarda hiçbir problem çekmedik. Vilnius ve Sucre'de ikişer defa denememize rağmen yine bir problemle karşılaşmadık. Bilmek istersiniz diye söylemek istedim.

@ShiningTodoroki Kodunuzu incelediğimde pit alanının X:40 ile X:120 arasında olduğunu gördüm, pit alanını daraltırsanız sorun çözülür diye düşünüyorum. Alternatif bir çözüm de şöyle: lap change zone gibi pit stop zone kontrolünü de ayrı bir şekilde ekleyebilirsiniz kendi kodunuza.
