### ISSUE TITLE
Hız kodlarıyla alakalı.

### ISSUE THREAD

**Issue by ShiningTodoroki** [thenorthstar/HaxBall-Simple-F1-Racing-Bot#4]
Merhabalar, bizim şu anki kodlarımızdaki ile sizin botunuzdaki kodlarınız arasında hız farkı var ve biz kod içerisinde hızı ayarlayan kısmı bilmediğimiz için elimiz kolumuz bağlı şu anda. Acaba pistteki hızı (karakter/avatar hızı) değiştirmemiz için hangi kısmı değişmemiz gerektiği konusunda bize yardımcı olabilir misiniz?

**Comment by thenorthstar** [comment]
> Merhabalar, bizim şu anki kodlarımızdaki ile sizin botunuzdaki kodlarınız arasında hız farkı var ve biz kod içerisinde hızı ayarlayan kısmı bilmediğimiz için elimiz kolumuz bağlı şu anda. Acaba pistteki hızı (karakter/avatar hızı) değiştirmemiz için hangi kısmı değişmemiz gerektiği konusunda bize yardımcı olabilir misiniz?

@ShiningTodoroki Ben direkt olarak oyuncu hızını kullanıyorum. Onların ne tarz bir fonksiyon kullandığı hakkında pek bir fikrim yok, onlara sormak lâzım.
