### ISSUE TITLE
I need help for a project

### ISSUE THREAD

**Issue by coutinhooooooooo** [thenorthstar/HaxBall-Simple-F1-Racing-Bot#5]
Hello, I wanted to know if anyone who likes racing or likes the bot, and knows how to program, can call me on discord, I've been wanting to do a project for months, please get in touch with coutinho#7593

**Comment by thenorthstar** [comment]
> Hello, I wanted to know if anyone who likes racing or likes the bot, and knows how to program, can call me on discord, I've been wanting to do a project for months, please get in touch with coutinho#7593

@coutinhooooooooo Hello bro. I have some links for you to let you reach more people who are either interested in F1 racing or bots. You can get help through the following servers:

**F1 Hax:** https://discord.gg/vfcWU2unzA
**F1 Turkey:** https://discord.gg/Vs36JzusbN
**HaxRacing:** https://discord.io/haxracing
**Racing with DJ:** https://discord.gg/SeTCkrg
