### ISSUE TITLE
DRS Enable/Disable

### ISSUE THREAD

**Issue by cockerelhub** [thenorthstar/HaxBall-Simple-F1-Racing-Bot#6]
Hello mate! I have an important problem and I need your help. I want DRS enabled after lap 3 in F1 race. This situation must be active with a difference of less than 1 second between you and your opponent. So if our normal speed is 80, it will increase to 85 when DRS is active. Thank you from now

**Comment by thenorthstar** [comment]
> Hello mate! I have an important problem and I need your help. I want DRS enabled after lap 3 in F1 race. This situation must be active with a difference of less than 1 second between you and your opponent. So if our normal speed is 80, it will increase to 85 when DRS is active. Thank you from now

@cockerelhub Hello dude, I have seen your issue but it can take a long time to do because of my business. Sorry about that, btw you can re-open the issue on **haxball-issues** wiki and look for a faster result as it has more visibility than here.

**Comment by thenorthstar** [comment]
> Hello mate! I have an important problem and I need your help. I want DRS enabled after lap 3 in F1 race. This situation must be active with a difference of less than 1 second between you and your opponent. So if our normal speed is 80, it will increase to 85 when DRS is active. Thank you from now

@cockerelhub Anymore the original script isn't modified unless there's any fatal issues like in the issue #8. As far as I remember, in the Spanish F1 bot room (Wild's one) it was using three kinds of tyres and I can say that it's a similar logic (certain zone and player damping adjustment) compared to that.
