### ISSUE TITLE
Script not functional after 1 race

### ISSUE THREAD

**Issue by cofimaslisa** [thenorthstar/HaxBall-Simple-F1-Racing-Bot#8]
I open the room, do 1 race and then i get like 20 times "Loaded Sucre from haxmaps" but its never loaded and the race never starts

**Comment by thenorthstar** [comment]
> I open the room, do 1 race and then i get like 20 times "Loaded Sucre from haxmaps" but its never loaded and the race never starts

@cofimaslisa OK, it's been fixed by changing the code. Here's the output:
![image](https://github.com/thenorthstar/HaxBall-Simple-F1-Racing-Bot/assets/68077608/26daabd7-dd6b-4b97-ab79-4d27e5491666)
