### ISSUE TITLE
Races

### ISSUE THREAD

**Issue by KeanoBroekhans** [thenorthstar/HaxBall-Simple-F1-Racing-Bot#9]
How can i change the maps that will be raced on? Do i need to delete and put something in the place where the circuit code is?

**Comment by thenorthstar** [comment]
> How can i change the maps that will be raced on? Do i need to delete and put something in the place where the circuit code is?

@KeanoBroekhans So,
- Firstly change the map codes through the main map variable (it starts with **var Circuit1 = ...**),
- Then you should change the map settings according to your new map (it starts with **var _Circuit1 = ...**)
- The most important things will be starting and driving directions. That's all.
